library(rvest)
library(dplyr)
library(robotstxt)
path=paths_allowed("https://www.imdb.com/list/ls003174642/")
link='https://www.imdb.com/list/ls003174642/'
web=read_html(link)
movie_name=web %>% html_nodes(".lister-item-header a") %>% html_text()
View(movie_name)
rating=web %>% html_nodes(".ipl-rating-star.small .ipl-rating-star__rating") %>% html_text()
View(rating)
director_name=web %>% html_nodes(".text-muted a:nth-child(1)") %>% html_text()
View(director_name)
top_horror_movies=data.frame(movie_name,rating,director_name)
View(top_horror_movies)
write.csv(top_horror_movies,"Top_horror_movies.csv")